"""
Event data model for exam monitoring.

This module provides data classes for storing exam events
generated by the rule engine.
"""

from dataclasses import dataclass
from typing import Optional, Dict, Any
from datetime import datetime

from app.events.event_types import EventType, EventSeverity


@dataclass
class ExamEvent:
    """Data class for a single exam event."""

    event_type: EventType
    severity: EventSeverity
    timestamp: float
    frame_number: int
    confidence: float
    description: str
    metadata: Optional[Dict[str, Any]] = None

    def to_dict(self) -> dict:
        """
        Convert event to dictionary.

        Returns:
            Dictionary representation of event
        """
        return {
            "event_type": self.event_type.value,
            "severity": self.severity.value,
            "timestamp": self.timestamp,
            "frame_number": self.frame_number,
            "confidence": self.confidence,
            "description": self.description,
            "metadata": self.metadata or {},
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ExamEvent":
        """
        Create ExamEvent instance from dictionary.

        Args:
            data: Dictionary containing event data

        Returns:
            ExamEvent instance
        """
        return cls(
            event_type=EventType.from_string(data["event_type"]),
            severity=EventSeverity.from_string(data["severity"]),
            timestamp=data["timestamp"],
            frame_number=data["frame_number"],
            confidence=data["confidence"],
            description=data["description"],
            metadata=data.get("metadata"),
        )


@dataclass
class FrameEvents:
    """Data class for all events in a single frame."""

    frame_number: int
    timestamp: float
    events: list[ExamEvent]

    def get_event_count(self) -> int:
        """
        Get number of events in frame.

        Returns:
            Number of events
        """
        return len(self.events)

    def get_events_by_type(self, event_type: EventType) -> list[ExamEvent]:
        """
        Get events of a specific type.

        Args:
            event_type: Event type to filter by

        Returns:
            List of events of the specified type
        """
        return [event for event in self.events if event.event_type == event_type]

    def get_events_by_severity(self, severity) -> list[ExamEvent]:
        """
        Get events of a specific severity.

        Args:
            severity: Severity to filter by (EventSeverity enum or string)

        Returns:
            List of events of the specified severity
        """
        # Handle both enum and string input
        severity_value = severity.value if hasattr(severity, 'value') else severity
        return [event for event in self.events if event.severity.value == severity_value]

    def has_critical_events(self) -> bool:
        """
        Check if frame has any critical events.

        Returns:
            True if critical events exist
        """
        return any(event.severity == EventSeverity.CRITICAL for event in self.events)

    def to_dict(self) -> dict:
        """
        Convert frame events to dictionary.

        Returns:
            Dictionary representation of frame events
        """
        return {
            "frame_number": self.frame_number,
            "timestamp": self.timestamp,
            "events": [event.to_dict() for event in self.events],
            "event_count": self.get_event_count(),
            "has_critical": self.has_critical_events(),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "FrameEvents":
        """
        Create FrameEvents instance from dictionary.

        Args:
            data: Dictionary containing frame events data

        Returns:
            FrameEvents instance
        """
        events = [ExamEvent.from_dict(e) for e in data.get("events", [])]
        return cls(
            frame_number=data["frame_number"],
            timestamp=data["timestamp"],
            events=events,
        )
