"""
Rule evaluator base class and interface.

This module provides the abstract base class for all rules
and the rule evaluator interface.
"""

from abc import ABC, abstractmethod
from typing import List
import time

from app.rules.context import RuleContext
from app.events.event import ExamEvent


class BaseRule(ABC):
    """Abstract base class for all rules."""

    def __init__(self, name: str):
        """
        Initialize rule.

        Args:
            name: Name of the rule
        """
        self.name = name

    @abstractmethod
    def evaluate(self, context: RuleContext) -> List[ExamEvent]:
        """
        Evaluate the rule against the context.

        Args:
            context: RuleContext containing detection and pose data

        Returns:
            List of ExamEvent objects generated by this rule
        """
        pass

    def __str__(self) -> str:
        """Return string representation of rule."""
        return f"{self.__class__.__name__}({self.name})"


class RuleEvaluator:
    """Evaluates all registered rules against a context."""

    def __init__(self):
        """Initialize rule evaluator."""
        self.rules: List[BaseRule] = []

    def register_rule(self, rule: BaseRule) -> None:
        """
        Register a rule for evaluation.

        Args:
            rule: Rule to register
        """
        if rule not in self.rules:
            self.rules.append(rule)

    def unregister_rule(self, rule: BaseRule) -> None:
        """
        Unregister a rule from evaluation.

        Args:
            rule: Rule to unregister
        """
        if rule in self.rules:
            self.rules.remove(rule)

    def evaluate_all(self, context: RuleContext) -> List[ExamEvent]:
        """
        Evaluate all registered rules against the context.

        Args:
            context: RuleContext containing detection and pose data

        Returns:
            List of all ExamEvent objects generated by all rules
        """
        all_events = []
        start_time = time.time()

        for rule in self.rules:
            try:
                events = rule.evaluate(context)
                all_events.extend(events)
            except Exception as e:
                # Log error but continue with other rules
                print(f"Error evaluating rule {rule.name}: {e}")

        evaluation_time = (time.time() - start_time) * 1000  # Convert to milliseconds

        return all_events

    def get_rule_count(self) -> int:
        """
        Get number of registered rules.

        Returns:
            Number of rules
        """
        return len(self.rules)

    def clear_rules(self) -> None:
        """Clear all registered rules."""
        self.rules.clear()
